package com.mooyle.goden.dao.mapper;

import com.mooyle.goden.domain.model.GodenUser;
import com.mooyle.goden.domain.model.GodenUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GodenUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    long countByExample(GodenUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int deleteByExample(GodenUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int insert(GodenUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int insertSelective(GodenUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    List<GodenUser> selectByExample(GodenUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    GodenUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GodenUser record, @Param("example") GodenUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GodenUser record, @Param("example") GodenUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GodenUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goden_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GodenUser record);
}