package com.mooyle.goden.domain.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   ç”¨æˆ·è¡¨
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goden_user
 */
public class GodenUser {
    /**
     * Database Column Remarks:
     *   ç”¨æˆ·å��ï¼Œæ‰‹æœºå�·ç �
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   MD5[MD5[passæ˜Žæ–‡+å›ºå®šsalt]+salt]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   å¤´åƒ�ï¼Œäº‘å­˜å‚¨çš„ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.head
     *
     * @mbg.generated
     */
    private String head;

    /**
     * Database Column Remarks:
     *   æ³¨å†Œæ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.register_date
     *
     * @mbg.generated
     */
    private Date registerDate;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡ç™»é™†æ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.last_login_date
     *
     * @mbg.generated
     */
    private Date lastLoginDate;

    /**
     * Database Column Remarks:
     *   ç™»é™†æ¬¡æ•°
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_user.login_count
     *
     * @mbg.generated
     */
    private Integer loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.id
     *
     * @return the value of goden_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.id
     *
     * @param id the value for goden_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.nickname
     *
     * @return the value of goden_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.nickname
     *
     * @param nickname the value for goden_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.password
     *
     * @return the value of goden_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.password
     *
     * @param password the value for goden_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.salt
     *
     * @return the value of goden_user.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.salt
     *
     * @param salt the value for goden_user.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.head
     *
     * @return the value of goden_user.head
     *
     * @mbg.generated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.head
     *
     * @param head the value for goden_user.head
     *
     * @mbg.generated
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.register_date
     *
     * @return the value of goden_user.register_date
     *
     * @mbg.generated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.register_date
     *
     * @param registerDate the value for goden_user.register_date
     *
     * @mbg.generated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.last_login_date
     *
     * @return the value of goden_user.last_login_date
     *
     * @mbg.generated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.last_login_date
     *
     * @param lastLoginDate the value for goden_user.last_login_date
     *
     * @mbg.generated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_user.login_count
     *
     * @return the value of goden_user.login_count
     *
     * @mbg.generated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_user.login_count
     *
     * @param loginCount the value for goden_user.login_count
     *
     * @mbg.generated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
}