package com.mooyle.goden.domain.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goden_users
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GodenUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_users.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_users.age
     *
     * @mbg.generated
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goden_users.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_users.id
     *
     * @return the value of goden_users.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_users.id
     *
     * @param id the value for goden_users.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_users.name
     *
     * @return the value of goden_users.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_users.name
     *
     * @param name the value for goden_users.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_users.password
     *
     * @return the value of goden_users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_users.password
     *
     * @param password the value for goden_users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_users.age
     *
     * @return the value of goden_users.age
     *
     * @mbg.generated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_users.age
     *
     * @param age the value for goden_users.age
     *
     * @mbg.generated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goden_users.school
     *
     * @return the value of goden_users.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goden_users.school
     *
     * @param school the value for goden_users.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school;
    }
}